name: "Go & Terraform Enterprise Deployment"

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: "1. pull latest git code"
        uses: actions/checkout@v4

      - name: "2. init go env"
        uses: actions/setup-go@v5
        with:
          go-version: '1.27.1'

      - name: "3. run unit test"
        run: go test ./...

      - name: '4. build docker image and add label'
        run: |
          docker build -t my-go-app:${{ github.sha }} .
          echo "image my-app-go:${{ github.sha }} pack success"

      - name: "5. install and config Terraform CLI tool"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: "6. driver init (terraform init)"
        working-directory: ./terraform
        run: terraform init

      - name: "7. generage upgrade plan (terraform plan)"
        working-directory: ./terraform
        run: terraform plan -var="app_version=${{ github.sha }}" -out=tfplan

      - name: "8. online update (terraform apply)"
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
